<?php

include('phpmailer.class.php');



if (isset($_POST['submit'])) {




    $mail = new PHPMailer();
    $mail2 = new PHPMailer();

    $mail->isSMTP();
    $mail->Host = 'smtp.gmail.com';
    $mail->SMTPAuth = true;
    $mail->Username = 'ckntalks@gmail.com'; //paste one generated by Mailtrap
    $mail->Password = 'erxgwpzrmzqyposn' //paste one generated by Mailtrap
    $mail->SMTPSecure = 'ssl';
    $mail->Port = 465;



    $mail->IsHTML(true);

    $mail->From = 'info@gramarhein.com';
    
    $reply_to = array($_POST['email']);
    $mail->FromName = $_POST['name'];

    $ip = $_SERVER['REMOTE_ADDR'];

         $mail->Subject = "Gramarhein-QUICK ENQUIRY FROM IP ".$ip;

    $toaddress = array('info@gramarhein.com', 'cknavas123@gmail.com');
       
     
    ob_start();

    $fields=array('name'=>'Name',
        'subject'=>'Subject',
'email'=>'Email',
'mob'=>'Phone',
'message'=>'Message',
   );

    require_once('emailer/Enquiry.php');
    $mail->Body = ob_get_contents();
    ob_end_clean();




    foreach ($toaddress as $toAddress) {
        $mail->AddAddress($toAddress);
    }
    foreach ($reply_to as $reply) {
        $mail->AddReplyTo($reply);
    }

    $mail->Send();






    $mail2->IsHTML(true);

    $mail2->From = 'no-reply@gramarhein.com';
    $mail2->FromName = 'Gramarhein';


    $mail2->Subject = "Your Enquiry Submitted Successfully";



    ob_start();
    require_once('emailer/Successful-message.php');
    $mail2->Body = ob_get_contents();
    ob_end_clean();

    $mail2->AddAddress($_POST['email']);

    $mail2->Send();
  header('location:../thank-you.html');
} 